FROM openjdk:8-jdk-alpine

COPY . /users-api
WORKDIR /users-api

# Install maven
RUN apk --no-cache add maven

# Build the service
RUN ./mvnw clean install
CMD JWT_SECRET=PRFT SERVER_PORT=8083 java -jar target/users-api-0.0.1-SNAPSHOT.jar